### ISSUE TITLE
Ability to customize the placeholder appearence

### ISSUE THREAD

**Issue by Frexuz** [antulik/pagelet_rails#10]
Would be cool to turn it off in an initializer. So I can write my own CSS. Even if I could override it at the moment, it's still a little bit of a 'waste' adding the current CSS to the DOM.

If this could be done, it would also be nice to get the full CSS in the readme, so we can copy and change it :)

Potentially, the initializer could give a full html template to override the placeholder view (`pagelet_loading_overlay.jst.ejs`)

Thoughts?

**Comment by antulik** [comment]
Are you talking about CSS which comes inside each placeholder? If so it's done for simplicity of use. And there is easy way to overwrite it. However I've realised that it is not documented.

```erb
<%= pagelet :pagelets_current_time, placeholder: { view: 'path_to_template' } %>
```

if you want global setting then you can use `pagelet_options` inside root controller

```ruby
class PageletController < ApplicationController
  include PageletRails::Concerns::Controller

  pagelet_options placeholder: { view: 'path_to_template' }
end

class CurrentTime::CurrentTimeController < ::PageletController
end
```

Does this help?

**Comment by Frexuz** [comment]
It would be even more awesome to do an initializer to make it for all pagelets, rather than for each one. But atleast this is enough to solve my case :) <3

**Comment by antulik** [comment]
in the example above you can do it for all pagelets with a single config

**Comment by Frexuz** [comment]
Oh right. I missed the inheritance :D Thanks!
