### ISSUE TITLE
pagelet_rails's executable "rails" conflicts with railties

### ISSUE THREAD

**Issue by n-rodriguez** [antulik/pagelet_rails#11]
Hi! I get this message when I do `gem install pagelet_rails`.

```sh
nicolas@desktop:~/PROJECTS/GITHUB_WIP$ gem install pagelet_rails
pagelet_rails's executable "rails" conflicts with railties
Overwrite the executable? [yN]  
```

I've introduced this bug in : https://github.com/antulik/pagelet_rails/commit/724767e824d131de2f2f55814327ecd9a72f0337

This override (and break) the `rails` command

**Comment by antulik** [comment]
I've just pushed new version `0.1.8`. Does it fix the problem?

**Comment by antulik** [comment]
After pushing the fix, i've realised that there is a better way to fix it, so redone it :)
