### ISSUE TITLE
html options (css class) not retained after rendering

### ISSUE THREAD

**Issue by Frexuz** [antulik/pagelet_rails#12]
`<%= pagelet :pagelets_my_pagelet, remote: true, html: { class: 'my-class' } %>`

`my-class` is correctly applied to the placeholder div, but is no longer there when the pagelet has rendered.

Is that by design, or a bug? :) I'd like to keep my class :D

**Comment by antulik** [comment]
I think that was recently fixed in the master branch. Could you please try it out and confirm if it works/doesn't.

**Comment by Frexuz** [comment]
Tested with master now. It seems to retain the class only with `remote: false`, `true` or `:turbolinks` loses the class.

**Comment by antulik** [comment]
Cool, thanks for checking, will do the fix in a day or so

**Comment by antulik** [comment]
@Frexuz should be fixed in 0.2.0 or master

**Comment by Frexuz** [comment]
Thank you! :D

**Comment by Frexuz** [comment]
Works
