### ISSUE TITLE
Partial refresh from outside the pagelet?

### ISSUE THREAD

**Issue by Frexuz** [antulik/pagelet_rails#14]
Is it possible to refresh a pagelet with javascript from somewhere outside of it?

My case: I'm trying to refresh a pagelet when I receive a websocket event.

**Comment by Frexuz** [comment]
At the moment, this is what I came up with:

Post an ajax request to somewhere, respond with a `.js.erb` and do:
`$('.pagelet-notifications_table-show').replaceWith('<%= j pagelet :pagelets_notifications_table, remote: false %>');`

Would be cool if there was a JS API exposed, like `$('.pagelet-notifications_table-show').data('api').refresh()` :D

**Comment by antulik** [comment]
You can use `PageletRails.loadPagelets(jQuery_selector)`. There has been internal refactoring in master branch to make pagelets easier to reload, so you might need to pull those changes.

The master branch also has new pagelet reload feature. There are no docs yet as the interface needs a bit of thinking. The example code is already in the demo project. Have a look here: https://github.com/antulik/pagelet_rails_demo_app/blob/master/app/pagelets/comments/comments_controller.rb#L6 and demo http://polar-river-18908.herokuapp.com/tabs/comments

The idea that you assign _tag_ to the pagelet and later you can trigger its refresh. Externally you can also do that with `PageletRails.tagsChanged(html_id, tags)` (html_id is the id of pagelet which triggered the change).

**Comment by Frexuz** [comment]
Oh nice, that looks so awesome! :) Even better than I imagined. The ability to update multiple _different_ pagelets with tags is very clever! :P

**Comment by Frexuz** [comment]
```
module Notifications

  class NotificationsController < PageletController

    include PageletRails::Concerns::Controller

    pagelet_resources only: [:index, :update]

    def index
      identified_by :notifications
      @unread_notifications = Notification.for(current_employee).unread_by(current_employee).decorate
    end

    def update
      notification = current_employee.notifications.find(params[:id])
      notification.mark_as_read!(for: current_employee)
      trigger_change :notifications
      render_response
    end

    private

    def render_response
      respond_to do |format|
        format.html { redirect_to notifications_path }
        format.js
      end
    end

  end

end
```

Link
`link_to 'Mark as read', pagelets_notification_path(notification), method: :put, remote: true)`

The trigger change doesn't seem to do anything. What am I missing? :)

**Comment by antulik** [comment]
Not sure yet, try 

```ruby
    def update
      notification = current_employee.notifications.find(params[:id])
      notification.mark_as_read!(for: current_employee)
      trigger_change :notifications

      redirect_to notifications_path
    end
```

**Comment by Frexuz** [comment]
Since the link is `remote: true`, we can't redirect there.
```
ArgumentError (wrong number of arguments (given 2, expected 0..1)):
app/pagelets/notifications/notifications_controller.rb:25:in `update'
```

and responding to `format.js` doesn't work either.

**Comment by antulik** [comment]
@Frexuz the provided information is not enough to debug the issue, so far everything looks good.

I've just tested similar example with `remote: true` for deleting comments in the demo project. Everything works as expected. E.g. 

```ruby
  # app/pagelets/comments/comments_controller.rb
  def destroy
    comment = Comment.find params[:id]

    if comment.destroy
      trigger_change :comments
    end
    
    redirect_to action: :index
  end
```
```
= link_to 'Delete', pagelets_comment_path(comment), method: :delete, remote: true
```
If you can provide sample project so the issue could be reproduced, I could give you more accurate reply.

**Comment by Frexuz** [comment]
Hi. Found out a few things. (I'll try to explain my scenario where this becomes a little less-ideal)

1. Redirecting must use `action:`, that wasn't clear :) It kinda works now, however..

My two pagelets share some functionality:
![image](https://user-images.githubusercontent.com/49692/28259323-49ed8a0a-6b08-11e7-8b22-2ac76930b459.png)

Normally, the `mark as read` links would link to the same `controller#action`, but now I can't do that. Instead I have to **duplicate** the update method in each pagelet.

```rb
    def update
      notification = current_employee.notifications.find(params[:id])
      notification.mark_as_read!(for: current_employee)
      trigger_change :notifications
      redirect_to action: :index
    end
```

this also means I can't use my decorator to re-use my link

```rb
class NotificationDecorator < Draper::Decorator
  # this can't no longer be reused because it has to link to different pagelets
  def mark_read_link
    link_to(t('notifications.notification.mark_as_read'), pagelets_notification_path(model), method: :put, remote: true) if notification_unread?
  end
end

<% cache notification do %>
  <tr>
    <td><%= notification.text %></td>
    <td><%= notification.mark_read_link # no :( %></td>
  </tr>
<% end %>
```

Would you recommend another approach? Or have any other ideas? :)

**Comment by Frexuz** [comment]
I went with linking the `mark as read` link to a separate (normal) controller via `remote: true`, then responding with js and using `PageletRails.tagsChanged`. Works very nicely :)

**Comment by antulik** [comment]
> Redirecting must use action:, that wasn't clear :) It kinda works now, however..

Redirecting could use any standard syntax, not just `action: ...`

> I went with linking the mark as read link to a separate (normal) controller via remote: true, then responding with js and using PageletRails.tagsChanged. Works very nicely :)

I think that's a good solution. As an idea you can move that extra controller inside one of the pagelets folder so the code is grouped. 

I can't think of anything else what you haven't mentioned yet. I had the similar problem with client side frameworks for web components. The solution was very similar and one of

- duplicate action (or use concerns in ruby)
- move to the parent component (or parent controller in ruby)
- handle separately (like you've done with separate controller, or extract logic to service object with duplicated action)

> What does the html_id do? I'm using undefined at this moment, and it works :)

when we want to refresh pagelets we want to exclude the pagelet which triggered the refresh to avoid double render, because it will be rendered as a part of the request. That `html_id` is identifier of the first pagelet. `undefined` is perfectly fine as long as you don't have html element with `id='undefined'` :)

**Comment by Frexuz** [comment]
Thanks for the explanations :) 
I think this is fine to close.
