### ISSUE TITLE
Can't get inline routing to work

### ISSUE THREAD

**Issue by Frexuz** [antulik/pagelet_rails#15]
My pagelet
```
module Notifications

  class NotificationsController < PageletController

    include PageletRails::Concerns::Controller

    pagelet_resources

    pagelet_routes do
      post :dismiss_notifications, to: 'notifications/notifications#dismiss'
    end

    # some other actions here ..

    def dismiss
      Notification.mark_as_read!(:all, for: current_employee)
    end

  end

end
```

Link, somewhere outside the pagelet.
`<%= link_to 'Dismiss all', pagelets_dismiss_notifications_path, method: :post, remote: true %>`

Error
`ActionController::RoutingError (uninitialized constant Notifications::Notifications):`

Rails routes gives me `/notifications/notifications/notifications`, is that right?
```
rails routes | grep dismiss
          pagelets_dismiss_notifications POST   /pagelets/dismiss_notifications(.:format)           notifications/notifications/notifications#dismiss
```

Not sure what I'm doing wrong :)

**Comment by antulik** [comment]
Because inline routes only make sense to define for the current pagelet it automatically scopes all routes as such so you don't have to (in your case the top `Notifications` module). Try

```ruby
    pagelet_routes do
      post :dismiss_notifications, to: 'notifications#dismiss'
    end
```
