### ISSUE TITLE
Listen for an pagelet arrived event?

### ISSUE THREAD

**Issue by Frexuz** [antulik/pagelet_rails#16]
I'd like to run some js when a pagelet has finished rendering. As the page-load code runs too early (before the pagelet ajax finishes). Would that be possible?

I'd prefer not to put a `<script>` inside pagelet views.

**Comment by antulik** [comment]
there javascript event `pagelet-loaded` which is triggered after the pagelet has finished loading. 

```javascript
$(document).on('pagelet-loaded', function() { 
  console.log('loaded') 
});
```
However currently the event does not pass the instance of the loaded pagelet. Arguments will be available in the next gem version.

**Comment by Frexuz** [comment]
Great :) Will wait for next version!
Keep issue open until then?

**Comment by antulik** [comment]
released 0.2.1. 

```javascript
$(document).on('pagelet-loaded', function(event, id, tags, content) { 
  console.log('loaded') 
});
```

**Comment by Frexuz** [comment]
<3 <3 <3

**Comment by Frexuz** [comment]
Would it be possible to get the name of the pagelet?

`<%= pagelet :pagelets_company_onboarding_progress, remote: true %>` would give me `company_onboarding_progress` as a parameter.

Looking at the source, im not sure which params are available.. 
`id = ActionController::Base.helpers.escape_javascript params[:target_container]`
https://github.com/antulik/pagelet_rails/blob/22b58866d55464f9bf1ceb2756ed43d151392d97/lib/pagelet_rails/concerns/response_wrapper.rb#L20

I could regex it from `content`, but not as nice :D

**Comment by antulik** [comment]
yes right now regex or jquery `$(content).attr('class')` are the best way to do it.

Please raise another issue as it might be more involved than a simple change.

**Comment by Frexuz** [comment]
Ok :)
