### ISSUE TITLE
Pagelet Response isn't updating the view.

### ISSUE THREAD

**Issue by jubeless** [antulik/pagelet_rails#4]
The pagelet is being generated and when I click on the link it sends out the Asynchronous request, it just doesn't wrap the response with `PageletRails.pageletArrived` so the HTML content isn't being updated. 

![image](https://cloud.githubusercontent.com/assets/1663997/19531991/b29724fc-95ee-11e6-93bc-d3c52f6533bb.png)

**Comment by antulik** [comment]
@jubeless have you included javascript file?
