### ISSUE TITLE
Rails 5 cache?

### ISSUE THREAD

**Issue by Frexuz** [antulik/pagelet_rails#5]
> update actionpack-action_caching gem to support rails 5

Does it mean that caching doesn't work with rails 5 at all?

If not, any ETA? :P

**Comment by antulik** [comment]
Cache currently works with rails 5. This is internal todo only. Internally it duplicates the code from the `actionpack-action_caching` gem as at the time dependencies for it were only for rails 4. 

Seems like there is new version of `actionpack-action_caching` was published 1.2.0 (January 23, 2017). So internally it possible to remove duplicate code now. https://github.com/rails/actionpack-action_caching/blob/master/CHANGELOG.md
