### ISSUE TITLE
undefined method `pagelet_params'

### ISSUE THREAD

**Issue by Frexuz** [antulik/pagelet_rails#9]
Seems I can't get the example pagelet to work. I thought the Rails 5.1 fix commit (73cf26bce2405ae88ba56544e22376192c249dc9) would work :/

Error:
`undefined method `pagelet_params' for #<CompaniesController:0x007f9a77786c48>`
in
`pagelet_rails-0529bb14c44d/app/helpers/pagelets_helper.rb:76:in 'pagelet'`

Gemfile.lock
```
GIT
  remote: git://github.com/antulik/pagelet_rails.git
revision: 0529bb14c44d7634f9615b565ee551b43e2837c5
```

app/pagelets/current_time/current_time_controller.rb
```
class CurrentTime::CurrentTimeController < ApplicationController
  include PageletRails::Concerns::Controller

  # add pagelets_current_time_path route
  # which gives "/pagelets/current_time" url route
  pagelet_resource only: [:show]

  def show
  end
end
```

`<%= pagelet :pagelets_current_time %>`

**Comment by antulik** [comment]
@Frexuz thanks for reporting, I've pushed fix to master branch. Give it a try.

**Comment by Frexuz** [comment]
Works :)
Will you release a new gem version any time soon?

**Comment by antulik** [comment]
already did 0.1.7

**Comment by Frexuz** [comment]
Great :) <3
